Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,95 +1,98 @@
-name: Deploy Application
+name: Deploy WordPress
+
 on:
-  workflow_dispatch: {}
   push:
     branches:
       - master
 
+
 jobs:
   build:
     runs-on: ubuntu-latest
-    outputs:
-      s3object: ${{ steps.object.outputs.s3object }}
-      
+    
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v4
+      uses: actions/checkout@v2
       
-    - uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-region: ${{ secrets.AWS_REGION }}
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
-      
-    - name: Create archive
-      id: object
+    - name: Package repo
       run: |
         git archive --format=tar.gz -o app_$(date +"%Y-%m-%d").tar.gz HEAD
-        s3object=$(echo "app_$(date +"%Y-%m-%d").tar.gz")
-        echo "s3object=$s3object" >> $GITHUB_OUTPUT
-        echo "S3 Object: $s3object"
-    - name: Upload to S3
+        
+    - name: push to bucket
       run: |
-        echo "Uploading to S3"
-        aws s3 cp app_$(date +"%Y-%m-%d").tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/
+       # mv app_$(date +%Y-%m-%d).tar.gz ${{ secrets.S3_BUCKET_NAME }}
+       aws s3 cp app_$(date +"%Y-%m-%d").tar.gz s3://${{ secrets.S3_BUCKET_NAME }}/
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: ${{ secrets.AWS_REGION }} 
     
-    - name: Set expiry policy on S3 bucket
+
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build 
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: deploy to ASG
       run: |
-        aws s3api put-bucket-lifecycle-configuration --bucket ${{ secrets.S3_BUCKET_NAME }} --lifecycle-configuration '{"Rules":[{"ID":"ExpireOldBuilds","Prefix":"","Status":"Enabled","Expiration":{"Days":7}}]}'
+        echo "Pushing to ASG"
+        instance_ids=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name  ${{ secrets.ASG_NAME }}  --query 'AutoScalingGroups[].Instances[].InstanceId' --output text)
+        echo $instance_ids
+        echo "${{ secrets.EC2_KEY }}" > KEY_PEM && chmod 600 KEY_PEM
+        cat KEY_PEM
+        echo $instance_ids 
+        
+        # instance_ids=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name  ${{ secrets.ASG_NAME }} --query 'AutoScalingGroups[].Instances[].InstanceId' --output text)
+        
+        for instance_id in $instance_ids; do
+          public_ip=$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[].Instances[].PublicIpAddress' --output text)
+  
+          ssh -o StrictHostKeyChecking=no -i KEY_PEM ubuntu@$public_ip "
+            cd /home/ubuntu
+            aws s3 cp s3://${{ secrets.S3_BUCKET }}/app_$(date +"%Y-%m-%d").tar.gz  .
+            sudo tar -xzvf app_$(date +"%Y-%m-%d").tar.gz
+            sudo systemctl restart apache2
+            "
+        done
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: ${{ secrets.AWS_REGION }} 
-##########################################################################################################
+        AWS_REGION: ${{ secrets.AWS_REGION }}
+        
 
-  deploy:
-    needs: build
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-region: ${{ secrets.AWS_REGION }}
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
-    - name: Deploy to Auto Scaling Group
-      env:
-        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_PEM }}
+        
+    - name: Generate presigned URL for S3 object
+      id: presigned_url
       run: |
-        # Get the instance IDs of instances in the Auto Scaling Group
-        export VMs=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name ${{ secrets.ASG_NAME }} --query 'AutoScalingGroups[].Instances[].InstanceId' --output text)
-        echo "VMs IDs: $VMs"
-        echo '${{ secrets.S3_BUCKET_NAME }}'
-        echo '${{ needs.build.outputs.s3object }}'
-        # object_url=$(aws s3 presign s3://${{ secrets.S3_BUCKET_NAME }}/${{ needs.build.outputs.s3object }})
-        # echo "Object URL: $object_url"
-        echo "${{ secrets.EC2_KEY }}" > EC2_KEY.pem  && chmod 600 EC2_KEY.pem
-        echo "s3object: ${{ needs.build.outputs.s3object }}"
-        # Iterate over each instance
-        for instance_id in $instance_ids; do
-          # Get the public IP address of the instance
-          public_ip=$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[].Instances[].PublicIpAddress' --output text)
-          # SSH into the instance and download the object from the S3 bucket
-          echo $public_ip
-             ssh -o StrictHostKeyChecking=no -i  EC2_KEY.pem ec2-user@$public_ip "
-            cd /var/www/html
-            pwd
-            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/app_2024-05-02.tar.gz  .
-            sudo tar -xvzf ${{ needs.build.outputs.s3object }}
-            ls
-            sudo rm -rf ${{ needs.build.outputs.s3object }}
-            sudo systemctl restart httpd
-            
-          
-            
-            "
-        done     
+         object_url=$(aws s3 presign s3://${{ secrets.S3_BUCKET }}/app_$(date +"%Y-%m-%d").tar.gz)
+         echo "Object URL: $object_url"
+         echo "::set-output name=url::$object_url"  # Set the URL as an output for later steps
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION: ${{ secrets.AWS_REGION }}
+
+    - name: Open URL in browser
+      if: success()
+      run: |
+         url="${{ steps.presigned_url.outputs.url }}"
+         # curl -sSL "$url" | xdg-open /dev/stdin  # Open the URL in the default web browser
+         xdg-open "$url" || echo "Unable to open URL"
+         echo "$url"
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION: ${{ secrets.AWS_REGION }}
 
 
-
-  
+    - name: Set S3 bucket expiry policy
+      run: |
+        aws s3api put-bucket-lifecycle-configuration --bucket ${{ secrets.S3_BUCKET }} --lifecycle-configuration '{"Rules":[{"ID":"DeleteObjectsAfter7Days","Prefix":"","Status":"Enabled","Expiration":{"Days":7}}]}'
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION: ${{ secrets.AWS_REGION }}
+       
